### ISSUE TITLE
accessing from event listener

### ISSUE THREAD

**Issue by NOaMTL** [nchaulet/ElephantIOBundle#5]
Is it possible to access to ElephantIO from an EventListener?
(i tried but it says : Attempted to call method "get" on class "Application\Sonata\UserBundle\EventListener\LoginListener".  )

**Comment by nchaulet** [comment]
you should inject `elephantio_client.your_service`service in your event listener 

you could find more documentation about this dependency injection here: 
http://symfony.com/fr/doc/current/book/service_container.html
