### ISSUE TITLE
Upgrade to wisembly/elephant.io 3.1.0

### ISSUE THREAD

**Issue by eparanyuk** [nchaulet/ElephantIOBundle#6]
Cound you upgrade bundle to working with last version wisembly/elephant.io? There are critical fixes in version 3.1.0 (https://github.com/Wisembly/elephant.io/pull/108). Thanks.

**Comment by nchaulet** [comment]
Sure I am going to give it a look this weekend.

**Comment by nchaulet** [comment]
Fixed with version 2.0.1
